### ISSUE TITLE
Procedure Appears Twice After Being Deleted and Another is Added

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#76] opened 2016-02-23 16:03 UTC
Locate a Procedure in the tree structure -> Right click on it and select Copy Procedure -> Paste the Procedure into another Domain, notice it appears as expected but without a Category -> Click on another tab and back again in order to redraw, notice it now appears with the correct Category -> Right click on and delete the Procedure -> Go to another Domain, find another Procedure with a different Category, right click and copy it -> Go back to the first Domain and paste into it, notice the newly copied Procedure appears twice in the Domain, once in the original category, and again with the new, correct Category.

**Comment by sbtaylor15** [comment] 2016-04-07 15:52
Retest since categories are being taken in to account

**Comment by rightker** [comment] 2016-04-07 22:50
Procedure doesn't paste into another Domain at all.

**Comment by pgibbs-openmake** [comment] 2016-04-10 19:47
This looks like a duplicate of #55 - should be fixed. Rebuild and retest required.

**Comment by sbtaylor15** [comment] 2016-04-14 19:35
Pass in 4/14 build

**Closed by sbtaylor15** 2016-04-14 19:35 UTC
Labels: bug
