### ISSUE TITLE
Bug Tracking Datasource field isn't loaded with values until edited

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#135] opened 2016-10-03 22:15 UTC
Deploy menu -> Components tab -> Right click on a Domain -> Select "New Component in this Domain" -> Entering values into fields, notice that the Bug Tracking Datasource field has no values in it. Click OK and then go back and edit the Bug Tracking Datasource field, now it has values.

**Comment by rightker** [comment] 2016-11-04 20:13
Looks like this is fixed but there are no comments to that effect (?)

**Comment by pgibbs-openmake** [comment] 2016-11-18 15:29
Cannot reproduce this. Suspect this may have been fixed by something else.

**Comment by sbtaylor15** [comment] 2016-11-21 18:57
Working in 20161121_615

**Closed by sbtaylor15** 2016-11-21 18:57 UTC
Labels: bug
